### PR TITLE
Runner

### PR DESCRIPTION
**Pull request by GlowMunch**
created new branch 'runner' because there was an error with naming the branch 'setup/runner'. Added to stat_tracker.rb
- .read_csv
- self.from_csv

### CODE REVIEW

**Review by Jesse193 — DISMISSED** [review]

**Review by Jesse193 — CHANGES_REQUESTED** [review]
The coverage should probably be removed

**Review by boomclear — APPROVED** [review]
I'm confused about all the coverage/ file adds, but it could be our gems.

**Review by boomclear — CHANGES_REQUESTED** [review]
We should investigate this coverage more.

**Comment by GlowMunch** [comment]
Closing for new pull request

**Pull request closed without merging**
